language: python
python:
- '3.6'
- '3.7'
install:
- pip install pipenv
- pipenv install --skip-lock
- pip install . -U
script:
- pytest
- black --check .
after_success:
- cd docs
- make html
- touch _build/html/.nojekyll
- cd -
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
    local_dir: docs/_build/html/
