language: python
python:
- '3.6'
install:
- sudo apt update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda env create -f environment.yml
- source activate cc
script:
- pytest
- black --check .
after_success:
- cd docs
- make html
- touch _build/html/.nojekyll
- cd -
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
    local_dir: docs/_build/html/
